spring:
  application:
    name: order-system
  datasource:
    url: jdbc:mysql://localhost:3307/order_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: Bf/ZBtc1ZQeYOIAioy/5pwdc6JN6UCztWaiPerTpxLM=
  expiration-ms: 86400000

order:
  timeout-seconds: 60

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    com.example.order: INFO
